### ISSUE TITLE
Legacy USB

### ISSUE THREAD

**Issue by JanX2** [angelXwind/make-mb41-osx#1]
This is just a hunch and haven’t tried this yet, but might the Legacy USB Injector Kext from work for running 10.11 on the MB 4,1?

<https://forums.macrumors.com/threads/macos-10-12-sierra-unsupported-macs-thread.1977128/>

**Comment by akemin-dayo** [comment]
Unfortunately, legacy USB will likely never work properly on macOS 10.11 and above on the MacBook4,1 due to its USB chipset actually being UHCI-based as opposed to OHCI-based.

When Apple rewrote the USB stack in macOS 10.11, no support for UHCI-based chipsets was added.

While it is actually possible to get USB support working on macOS 10.11 (and theoretically above) by flat-out replacing the USB stack with macOS 10.10's, but that is a method that I personally do not agree with, so make-mb41-osx will likely only ever support up to 10.10.5 properly.

In any case, closing this issue now.

**Comment by HeIIoween** [comment]
Noticed that install 10.11 runs with usb wireless mouse

**Comment by HeIIoween** [comment]
Noticed that install 10.11 runs with usb wireless mouse starting from Clover boot loader and removing all DSDT fixes at it's options
